# Generated by Django 4.2.13 on 2024-06-10 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(choices=[('JP23', 'JP23'), ('KP5', 'KP5'), ('TS17', 'TS17')], max_length=4)),
                ('department', models.CharField(choices=[('kitchen', 'Kitchen'), ('terminal', 'Terminal'), ('driver', 'Driver')], max_length=10)),
                ('shift', models.CharField(choices=[('lunch', 'Lunch shift'), ('evening', 'Evening shift')], max_length=10)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='KitchenTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make_juice_completed', models.BooleanField(default=False)),
                ('make_pizza_completed', models.BooleanField(default=False)),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kitchen_task', to='tasks.task')),
            ],
        ),
    ]
