# Generated by Django 4.2.13 on 2024-06-10 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KitchenTask',
        ),
    ]
