# Generated by Django 4.2.13 on 2024-06-10 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_delete_kitchentask'),
    ]

    operations = [
        migrations.CreateModel(
            name='KitchenTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make_juice_completed', models.BooleanField(default=False)),
                ('make_pizza_completed', models.BooleanField(default=False)),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kitchen_task', to='tasks.task')),
            ],
        ),
    ]
