# Generated by Django 4.2.13 on 2024-06-10 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_kitchentask'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='all_completed_checkbox',
            field=models.BooleanField(default=False),
        ),
    ]
