# Generated by Django 4.2.13 on 2024-06-10 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_rename_all_completed_checkbox_task_all_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='all_completed',
        ),
    ]
